### PR TITLE
Update r-sjstats to 0.17.2

### PR DESCRIPTION
**Pull request by apcamargo**

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by ccwang002** [comment]
There are two PRs for the same version but they seem to do the same thing. @apcamargo and @philip-khor, which one should I use?

**Comment by apcamargo** [comment]
@philip-khor seems to have updated the versions of the required packages. I'd merge his PR.

**Comment by ccwang002** [comment]
Merged PR #6 instead. Thanks for your help!

**Pull request closed without merging**
